### Exercise 2
#### By Cooper Nederhood

#### Part (a):

In [7]:
#import packages 
import numpy as np
import pandas as pd
import scipy.stats as sts
import os
import matplotlib.pyplot as plt
import scipy.optimize as opt
from scipy import special
from scipy.integrate import quad
from scipy.stats import norm

In [12]:
data = np.loadtxt('MacroSeries.txt', delimiter=",")
beta = 0.99
c = data[:, 0]
k = data[:, 1]
w = data[:, 2]
r = data[:, 3]

In [18]:
# Set initial vals
alpha0 = 0.5
rho0 = 0.5
mu0 = 8
sigma0 = 0.5
params0 = (alpha0, rho0, mu0, sigma0)

In [19]:
# Define functions
def calc_z(w, alpha, k):
    z = np.log(w) - np.log(1-alpha) - alpha*np.log(k) 
    
    return z 

def norm_pdf(z, rho, mu, sigma):
    z[0] = mu
    mean = rho * z[:-1] + (1 - rho) * mu
    params = np.hstack([mu, mean])
    logpdf_vals = norm.pdf(z, params, sigma)
    
    return logpdf_vals

def crit_fn1(params, *args):
   
    alpha, rho, mu, sigma = params
    w, k  = args
    z = calc_z(w, alpha, k)
    pdf_vals = np.log(norm_pdf(z, rho, mu, sigma))
    
    return -pdf_vals.sum()

In [25]:
bounds = ((1e-6, 1-1e-6), (-1+1e-6, 1-1e-6),(1e-6, None), (1e-6, None))

results1 = opt.minimize(crit_fn1, params0, args=(w, k), method ='L-BFGS-B', bounds=bounds)
alpha1, rho1, mu1, sigma1 = results1.x
print("Results are:")
print(results1)
print("\nAnd inv hessian (with to-dense):")
print(results1.hess_inv.todense())

Results are:
      fun: -95.55298518258294
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([-0.01463576, -0.00019327, -0.00170104,  0.00201652])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 300
      nit: 43
   status: 0
  success: True
        x: array([0.85065892, 0.51750033, 4.56650362, 0.09306403])

And inv hessian (with to-dense):
[[ 2.95649136e+00 -2.12097567e+00 -2.72434964e+01 -7.24709999e-02]
 [-2.12097567e+00  5.83080835e+00  1.98503940e+01  2.64243645e-01]
 [-2.72434964e+01  1.98503940e+01  2.51066077e+02  6.82983897e-01]
 [-7.24709999e-02  2.64243645e-01  6.82983897e-01  1.23027885e-02]]


#### Part (b):

In [26]:
# Write new functions
def calc_z_partb(r, k, alpha):
    
    z = np.log(r) - np.log(alpha) - (alpha-1)*np.log(k)
    
    return z 

def crit_fn_partb(params, *args):
   
    alpha, rho, mu, sigma = params
    w, k  = args
    z = calc_z_partb(r, k, alpha)
    pdf_vals = np.log(norm_pdf(z, rho, mu, sigma))
    
    return -pdf_vals.sum() 

In [27]:
bounds = ((1e-6, 1-1e-6), (-1+1e-6, 1-1e-6),(1e-6, None), (1e-6, None))

results2 = opt.minimize(crit_fn_partb, params0, args=(w, k), method ='L-BFGS-B', bounds=bounds)
alpha2, rho2, mu2, sigma2 = results2.x
print("Results are:")
print(results1)
print("\nAnd inv hessian (with to-dense):")
print(results2.hess_inv.todense())

Results are:
      fun: -95.55298518258294
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([-0.01463576, -0.00019327, -0.00170104,  0.00201652])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 300
      nit: 43
   status: 0
  success: True
        x: array([0.85065892, 0.51750033, 4.56650362, 0.09306403])

And inv hessian (with to-dense):
[[ 7.13090174e-01 -9.74626965e-02 -1.26912201e+01 -3.89786071e-02]
 [-9.74626965e-02  1.00508058e+00  2.53428467e+00  7.95132968e-02]
 [-1.26912201e+01  2.53428467e+00  2.26528805e+02  7.58725887e-01]
 [-3.89786071e-02  7.95132968e-02  7.58725887e-01  1.01326025e-02]]


/home/cooper/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log
  del sys.path[0]
/home/cooper/anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py:643: RuntimeWarning: invalid value encountered in double_scalars
  grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]


#### Part (c):

In [30]:
z = calc_z(1, 7500000, alpha2)
mean = rho2 * 10 + (1 - rho2) * mu2
print('Probability : ',  1-norm.cdf(z, mean, sigma2))

Probability :  nan


/home/cooper/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until
